set_property PACKAGE_PIN R14 [get_ports c]
set_property IOSTANDARD LVCMOS33 [get_ports c]
set_property IOSTANDARD LVCMOS33 [get_ports b]
set_property IOSTANDARD LVCMOS33 [get_ports a]
set_property PACKAGE_PIN R19 [get_ports a]
set_property PACKAGE_PIN T19 [get_ports b]
