# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/top/top.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top || ORIG_REF_NAME==top} -quiet] -quiet

# IP: bd/top/ip/top_processing_system7_0_0/top_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_processing_system7_0_0 || ORIG_REF_NAME==top_processing_system7_0_0} -quiet] -quiet

# XDC: c:/Users/pala8831/Documents/fpga_multiplexing/zturn_base_project/zturn_base_project.gen/sources_1/bd/top/top_ooc.xdc
