set_property SRC_FILE_INFO {cfile:C:/Users/pala8831/Documents/fpga_multiplexing/and_gate/and_gate.srcs/constrs_1/new/contraints.xdc rfile:../../../and_gate.srcs/constrs_1/new/contraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R14 [get_ports c]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R19 [get_ports a]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T19 [get_ports b]
