set_property SRC_FILE_INFO {cfile:C:/Users/pala8831/Documents/fpga_multiplexing/clock_out/clock_out.srcs/constrs_1/new/constraints.xdc rfile:../../../clock_out.srcs/constrs_1/new/constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U14 [get_ports clk]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K14 [get_ports pin_out]
