set_property IOSTANDARD LVCMOS33 [get_ports a]
set_property IOSTANDARD LVCMOS33 [get_ports c]
set_property PACKAGE_PIN R14 [get_ports c]
set_property PACKAGE_PIN U20 [get_ports a]
set_property PACKAGE_PIN Y18 [get_ports b]
set_property IOSTANDARD LVCMOS33 [get_ports b]
